version: '3.3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
  app:
    container_name: 'app'
    build: "./TrueToSizeCalculationService"
    volumes:
      - ./TrueToSizeCalculationService:/go/src/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    links: 
      - db
  web:
    container_name: 'web'
    image: 'nginx:latest'
    build: './web'
    ports:
      - '80:80'
    volumes:
      - './web:/usr/share/nginx/html'

  